#!/bin/bash
#SBATCH --job-name=executor
#SBATCH --time=00:30:00
#SBATCH --qos=30min
#SBATCH --cpus-per-task=1
#SBATCH --mem=3G
#SBATCH --output=/dev/null 
#SBATCH --error=/dev/null 

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
source /scicore/home/lilienfeld/rudorff/.executor
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/scicore/home/lilienfeld/rudorff/opt/conda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/scicore/home/lilienfeld/rudorff/opt/conda/etc/profile.d/conda.sh" ]; then
        . "/scicore/home/lilienfeld/rudorff/opt/conda/etc/profile.d/conda.sh"
    else
        export PATH="/scicore/home/lilienfeld/rudorff/opt/conda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
conda activate redis-worker

cd /scicore/home/lilienfeld/rudorff/workcopies/bookkeeper/executor2/ 
python worker.py &> /dev/null
